### ISSUE TITLE
ImportError: No module named rrt_exploration.msg

### ISSUE THREAD

**Issue by lrxiao** [fazildgr8/ros_autonomous_slam#1]
why I get the error "ImportError: No module named rrt_exploration.msg"when I use roslaunch ros_autonomous_slam autonomous_explorer.launch?Can anyone help me,thanks!

**Comment by kvnptl** [comment]
change below line, https://github.com/fazildgr8/ros_autonomous_slam/blob/56fff100b3c09d94992350020f61cf134240ed2a/scripts/assigner.py#L10

to (basically write package name)

`from ros_autonomous_slam.msg import PointArray`

**Comment by fazildgr8** [comment]
> change below two lines,
> 
> https://github.com/fazildgr8/ros_autonomous_slam/blob/56fff100b3c09d94992350020f61cf134240ed2a/scripts/assigner.py#L10
> 
> 
> https://github.com/fazildgr8/ros_autonomous_slam/blob/56fff100b3c09d94992350020f61cf134240ed2a/scripts/filter.py#L14
> 
> to (basically write package name)
> 
> `from ros_autonomous_slam.msg import PointArray`

Thankyou I had the official rrt_exploration package installed side which also has the same msg by so this wasn't creating an issue previously.
